nodejs_version: "16.x"
npm_config_prefix: "/usr/local/lib/npm"
npm_config_unsafe_perm: "false"
nodejs_npm_global_packages: 
  - name: forever

nodejs_package_json_path: ""
nodejs_generate_etc_profile: "true"
node_apps_location: /usr/local/opt/node


user_home_dir: /home/vagrant